runtime: nodejs
env: flex

env_variables:
  SQL_USER: Nero
  SQL_PASSWORD: Mysql@2210
  SQL_DATABASE: facebook_rating
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: quiet-grail-176206:us-central1:nero-db
  SQL_CLIENT: mysql
